version: "3"
services:
    workshop-php:
        image: "pauulog/php-docker-dev:latest"
        container_name: "lasso-php"
        links:
          - "lasso-mariadb:mariadb.host"
        volumes:
            - "./:/h3-back:rw"
        working_dir: /h3-back
        restart: always
    workshop-nginx:
        image: "nginx:1-alpine"
        container_name: "lasso-nginx"
        links:
          - "lasso-php:lasso-php.host"
        ports:
          - 8081:80
        volumes:
            - "./:/h3-back:rw"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:r"
        working_dir: /h3-back
        restart: always
    workshop-mariadb:
        image: "mariadb:10.6"
        container_name: "lasso-mariadb"
        volumes:
            - "._mysql_data_dir/:/var/lib/mysql:rw"
        ports:
          - 3308:3306
        environment:
          - MARIADB_USER
          - MARIADB_PASSWORD
          - MARIADB_DATABASE
          - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
        restart: always