<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGMkScHq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGMkScHq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGMkScHq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGMkScHq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGMkScHq\App_KernelDevDebugContainer([
    'container.build_hash' => 'GMkScHq',
    'container.build_id' => 'cd5fc16b',
    'container.build_time' => 1647901144,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGMkScHq');
