<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2ZTmd6M\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2ZTmd6M/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2ZTmd6M.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2ZTmd6M\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2ZTmd6M\App_KernelDevDebugContainer([
    'container.build_hash' => '2ZTmd6M',
    'container.build_id' => '6243a49a',
    'container.build_time' => 1647818302,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2ZTmd6M');
