<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRWwmPlX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRWwmPlX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRWwmPlX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRWwmPlX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRWwmPlX\App_KernelDevDebugContainer([
    'container.build_hash' => 'RWwmPlX',
    'container.build_id' => '1154f4f9',
    'container.build_time' => 1647777580,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRWwmPlX');
